plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

title: In a nutshell
tagline: Cédric Eyssette - Blog Philosophie, Pédagogie, Numérique
author: Cédric Eyssette
description: Professeur de philosophie
avatar: /avatar.jpg
email: c%6&#53;%64%&#55;2ic&#46;&#101;%79&#37;73%73&#37;&#54;5&#116;%74e&#64;g&#109;ai%6C&#46;%6&#51;om
lang: fr
skin: daylight

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec


twitter:
  username: Cedric_Eyssette
  card: summary
logo: avatar.jpg
social:
  name: Cédric Eyssette
  links:
    - https://twitter.com/Cedric_Eyssette
    - https://www.facebook.com/cedric.eyssette
    - https://eyssette.github.io/
